import numpy as n
a=n.array([54,78,32,46,89,76])
print("\nAn Array:",a)
print("\nSum:",n.sum(a))
print("Product",n.prod(a))
print("Mean:",n.mean(a))
print("Standard Deviation:",n.std(a))
print("Variance",n.var(a))
print("Minimum Value:",n.min(a))
print("Max:",n.max(a))
print("Min Index:",n.argmin(a))
print("Max Index:",n.argmax(a))
print("Median:",n.median(a))
print("Product:",n.prod(a))